### ISSUE TITLE
error when converting point cloud [raise convert_to_error(kind, result)]

### ISSUE THREAD

**Issue by fujenchu** [microsoft/HoloLens2ForCV#128]
Hi All,

I tried to follow the official website and process the HL2 collected data.
https://docs.microsoft.com/en-us/samples/microsoft/hololens2forcv/stream-recorder-sample/

However, when I ran `process_all.py`, I got issues as follow:
```
 File "C:\Python36\lib\multiprocessing\managers.py", line 772, in _callmethod
    raise convert_to_error(kind, result)
KeyError: 0
```

I am assuming this is related to multiple processing but it seems only happen to my PC? I didn't get a chance to try other machine tho (and not seeing this in other issues)

A full log:
```
C:\Users\fujenchu\Documents\projects\github\HoloLens2ForCV_replay\Samples\StreamRecorder>python3 StreamRecorderConverter/process_all.py --recording_path sample/8-10-21
Extracting sample\8-10-21\Depth Long Throw.tar
Extracting sample\8-10-21\PV.tar
Processing images
..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Saving point clouds
...........................Traceback (most recent call last):
  File "StreamRecorderConverter/process_all.py", line 56, in <module>
    process_all(w_path, args.project_hand_eye)
  File "StreamRecorderConverter/process_all.py", line 38, in process_all
    save_pclouds(w_path, sensor_name)
  File "C:\Users\fujenchu\Documents\projects\github\HoloLens2ForCV_replay\Samples\StreamRecorder\StreamRecorderConverter\save_pclouds.py", line 340, in save_pclouds
    save_output_txt_files(pinhole_folder, shared_dict)
  File "C:\Users\fujenchu\Documents\projects\github\HoloLens2ForCV_replay\Samples\StreamRecorder\StreamRecorderConverter\save_pclouds.py", line 42, in save_output_txt_files
    for timestamp in shared_dict:
  File "<string>", line 2, in __getitem__
  File "C:\Python36\lib\multiprocessing\managers.py", line 772, in _callmethod
    raise convert_to_error(kind, result)
KeyError: 0

```

**Comment by ahahaha10** [comment]
python 3.6.9
open3d 0.15.1
opencv-python 4.5.4.60
numpy  1.19.5
